### ISSUE TITLE
Useable Console Output 

### ISSUE THREAD

**Issue by petervandivier** [taddison/SQLSpelunker#1]
Would be nice to be able to manipulate the output as an object or even just a comma-separated string? `¯\_(ツ)_/¯`

**Comment by taddison** [comment]
It is exposed as an object (specifically https://github.com/taddison/SQLSpelunker/blob/master/src/SQLSpelunker.Core/ProcedureCall.cs).  I guess you could leverage this DLL from PowerShell directly (or build a cmdlet and ship that?).

The console output was really to enable eyeballing the chain more than anything directly useful - adding an additional ouput style (with optional format) would be fairly easy if you had something in mind (Id, DB, Schema, Object, CalledById, Depth, IsInfiniteLoop?), though whether that should be direct in the app vs. implemented by consuming the DLL depends on what you had planned.
